# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://skodali1.github.io
title: Sigmoid Freud
email: kodalisushanth@gmail.com
description: This Blog was started to explore ideas and projects I have when it comes to Data Science.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SushanthKodali
  - title: github
    url: https://github.com/skodali1
  - title: linkedin
    url: https://www.linkedin.com/profile/view?id=55279779&trk=nav_responsive_tab_profile
